travis:
  secure:
    BINSTAR_TOKEN: daEsVOtJgF/k2PhAU07kopgYWiMGC4Iajs2qnR08F2fs4VzATBc7dW0MqlPQLknFnv/mSI5nwiZOBUWL+nVYYo7AFwmhEFj8HUAsvJDhbmclNWvNo8rb0xGqidFhnbjKIp8uzsMw7164Yq55Zyj9MRa/+fmnpL1e+Wp2rHS5cM/PAT62u8sFro20278MkChtfrR8WZSIeTTjBm0lGjYNZsyW8kC/CX4q5Q1SVm6cefmFFgCVNbc5XPaAPhbcugZ31c9fjQ68MeMGs9BWQwtsI6C7DJ8wee/1fZfDOFcgvjQyxDK34oqCu5uYBTeSpCjlrtty8PuP4wWZq+AYcBgWW+QVDcruKL6Q0lHhvZxpEA5v3JKnt2HEmNHb/0ypaLNlwfb+jiKnwqF4woQA4eg7e5zps+foZWOeUSODbfFBpxKyM0y+nYQjLAN48BHnGpFphVijysCcY0KLkwIQkmz36PDGqlapP0tNWOvPCkAYUTnW74J4Ur91PPk4wjmpWldWZPV53foo+4u1t06Q2pZgVTkQ9dlYzjPuGtrUM4UvKNTentbmQQ4GCT6lppMmMdQXtedzAOD9e92GWu/rM8DgtulNP/vuUXSd57gCt9uV8ppJcrjqPXP0quwNLDWZW7CxpJ4gvWGMruUmnKyqDxmrkn0QGQyFjcHhnkM0SpW2Erk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
